### PR TITLE
Evict connection from pool on NetSocket close

### PR DESCRIPTION
**Pull request by stampy88**
Version: 3.9.0 and 4.0.0-SNAPSHOT

There is currently an issue where when a NetSocket is closed, the connection is not evicted from the pool. This is easy to product by enabling client-side timeouts
on the Redis server [https://redis.io/topics/clients#client-timeouts]. Because the connection is not being evicted, the next time it is given out you will see a
`CONNECTION_CLOSED` error when trying to use said conncection.

This fix evicts the connection on `NetScoket` close.

Signed-off-by: dave sinclair <stampy88@yahoo.com>

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test for this @stampy88 ?

**Comment by stampy88** [comment]
Yup, @vietj pushed

**Comment by stampy88** [comment]
Looks like master has the same issue. Let me know if you want a separate PR, or you'll cherry-pick this yourself @vietj

**Comment by pmlopes** [comment]
Hi @stampy88 no worries, after the review I'll cherry pick it.

**Comment by pmlopes** [comment]
This fix is applied to 3.9.1 and cherry picked to 4.0.0

**Comment by pmlopes** [comment]
Thanks @stampy88

**Pull request merged**
