### PR TITLE
Initial support for pool metrics

### LINKED ISSUE #195: Client metrics
We should support metrics for this client and have latencies measurement for operations, also good to know how long operations are queued.

### PR DESCRIPTION
**Pull request by pmlopes**
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

Motivation:

Fixes #195

### CODE REVIEW

**Comment by pmlopes** [comment]
This PR implements the basic pool metrics support for redis, just like in jdbc client.

**Review by vietj — COMMENTED** [review]
Can you add a test that checks the metrics is closed when the client is closed ?

**Comment by pmlopes** [comment]
@vietj the `lifecycle` test checks this. After the client is closed it asserts that there are no more pool metrics objects (as the close removes the metric object).

**Review by vietj — APPROVED** [review]
LGTM

**Pull request merged**
