### PR TITLE
Add support for domain socket

### PR DESCRIPTION
**Pull request by BillyYccc**
Signed-off-by: BillyYccc <billy112487983@gmail.com>

This work is for Issue #90 , make it possible to use domain socket in Redis client.

### CODE REVIEW

**Comment by vietj** [comment]
have you tested it ?

**Comment by BillyYccc** [comment]
@vietj Yeah, I have tested this in Ubuntu 16.04, it seems to works fine with Redis 4.0.2.

**Comment by vietj** [comment]
ok we will merge the PR after 3.5.0 release, as for now it's too late to have it, it shall be in 3.5.1.

the concern I have is the declaration in options of domain socket, currently we don't provide a way to have a default socket address for domain sockets and I believe it is fine because one can use `NetClient#connect(SocketAddress)`, so if the `RedisClient` has a similar connect method it would be enough I think.

**Comment by BillyYccc** [comment]
The vertx-redis-client at present uses a mechanism of automatic reconnection, the client connects to Redis server as soon as it is created with a config. Therefore I think if we use a new connect method like `RedisClient#connect(SocketAddress)`, this might bring breaking changes to the users. WDYT?

**Comment by vietj** [comment]
I think that simply overloading 

```
static RedisClient create(Vertx vertx, RedisOptions config, SocketAddress address)
```

would be enough overall

**Comment by pmlopes** [comment]
It’s a bigger discussion than just this issue but I think that in our APIs where we have ‘options, otherType’ in the create methods it feels like a code smell since the options are not a good data structure to define all options as we still need to depend on other data types and variables to configure the way we want the object to behave.

**Comment by pmlopes** [comment]
I think the issue #68 needs to be prioritized as it starts to make more sense. API independence and full control over the connection, no lazy connect, no auto reconnect. The user would have control over this behavior (which is not available) currently.

**Comment by vietj** [comment]
@pmlopes I agree with you, that it's good to provide a simple API like RedisClient and also something that provides more control like a `RedisConnection`

Overall we could adopt the same pattern we introduced for `SQLClient` and have a `RedisOperations` interface that is both on `RedisConnection` and `RedisClient`.

**Comment by BillyYccc** [comment]
Thanks for reviewing!

**Pull request merged**
