### PR TITLE
Adding support for Redis Sentinel, failover implementation

### PR DESCRIPTION
**Pull request by ajaysarda**
Sending across new pull request for issue https://github.com/vert-x3/vertx-redis-client/issues/19

### CODE REVIEW

**Comment by ajaysarda** [comment]
@pmlopes Does this change look fine?

**Comment by pmlopes** [comment]
@ajaysarda I haven't had enough time to review it yet, i'll try to do in the coming days.

**Comment by ajaysarda** [comment]
@pmlopes. Any chance, if we can get this out soon. I just don't want for this review to get outdated with other new changes to repo.

**Comment by pmlopes** [comment]
@ajaysarda we've been busy with the 3.1 this feature will be for sure in 3.2 ;)

**Comment by ajaysarda** [comment]
Thanks @pmlopes for reviewing this. I will work on it this weekend and resend updated one.

**Comment by pmlopes** [comment]
Why did you close this? I just started migrating your pr to the current code 3 days ago

**Comment by brianjcj** [comment]
when will this feature get ready?

**Comment by brianjcj** [comment]
It seems this implementation does not follow the Guidelines for Redis clients with support for Redis Sentinel: http://redis.io/topics/sentinel-clients

**Comment by pmlopes** [comment]
This has been merged as:

https://github.com/vert-x3/vertx-redis-client/pull/80

**Pull request closed without merging**
